services:
  eden-memory-game-backend:
    env_file:
      - .env
    build: .
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
